// stubs/vue/media-manager.vue
<script setup lang="ts">
import { MediaManagerPage } from '@inlayphp/media-manager-vue';
import type { MediaManagerPageProps } from '@inlayphp/media-manager-vue';
import InlayPanelLayout from '../../layouts/inlay-panel-layout.vue';

defineProps<MediaManagerPageProps>();
</script>

<template>
    <InlayPanelLayout>
        <MediaManagerPage v-bind="$props" />
    </InlayPanelLayout>
</template>

// stubs/react/media-manager.tsx
import { MediaManagerPage } from "@inlayphp/media-manager-react";
import type { MediaManagerPageProps } from "@inlayphp/media-manager-react";
import InlayPanelLayout from "../../layouts/inlay-panel-layout";

export default function MediaIndex(props: MediaManagerPageProps) {
  return (
    <InlayPanelLayout>
      <MediaManagerPage {...props} />
    </InlayPanelLayout>
  );
}
