// stubs/vue/users-index.vue
<script setup lang="ts">
import { Head, Link, usePage } from '@inertiajs/vue3';
import { computed } from 'vue';
import type { PanelResource } from '@inlayphp/panels-vue';
import { ResourcePage } from '@inlayphp/resources-vue';
import type { ResourceBreadcrumb, ResourceSubNavigationItem, ResourceTabsResource } from '@inlayphp/resources-vue';
import { Table } from '@inlayphp/tables-vue';
import type { TableResource } from '@inlayphp/tables-vue';
import InlayPanelLayout from '../../layouts/inlay-panel-layout.vue';

type PageProps = {
    inlayPanel: PanelResource;
    breadcrumbs?: ResourceBreadcrumb[];
    heading: string;
    subheading?: string | null;
    subNavigation?: ResourceSubNavigationItem[];
    table: TableResource;
    tabs?: ResourceTabsResource | null;
};

defineProps<PageProps>();
const page = usePage<PageProps>();
const theme = computed(() => ({
    contract: 'inlay.themes.v1' as const,
    name: page.props.inlayPanel.themeName ?? page.props.inlayPanel.id,
    tokens: page.props.inlayPanel.theme,
    darkTokens: page.props.inlayPanel.darkTheme ?? {},
}));
</script>

<template>
    <InlayPanelLayout>
        <Head :title="heading" />
        <ResourcePage
            :breadcrumbs="breadcrumbs ?? []"
            :heading="heading"
            :sub-navigation="subNavigation ?? []"
            :subheading="subheading ?? 'Create and maintain panel accounts.'"
            :tabs="tabs ?? null"
        >
            <template #actions>
                <Link
                    class="inline-flex min-h-(--inlay-button-height) items-center rounded-(--inlay-radius) bg-(--inlay-accent) px-4 text-sm font-semibold text-(--inlay-accent-foreground) transition hover:opacity-90"
                    href="/{{ panel }}/users/create"
                >
                    Create user
                </Link>
            </template>
            <section class="rounded-(--inlay-radius) border border-(--inlay-border) bg-(--inlay-surface) p-4 sm:p-6">
                <Table :resource="table" :theme="theme" />
            </section>
        </ResourcePage>
    </InlayPanelLayout>
</template>

// stubs/react/users-index.tsx
import { Head, Link, usePage } from "@inertiajs/react";
import { ResourcePage } from "@inlayphp/resources-react";
import type {
  ResourceBreadcrumb,
  ResourceSubNavigationItem,
  ResourceTabsResource,
} from "@inlayphp/resources-react";
import { Table } from "@inlayphp/tables-react";
import type { PanelResource } from "@inlayphp/panels-react";
import type { TableResource } from "@inlayphp/tables-react";
import InlayPanelLayout from "./inlay-panel-layout";

type PageProps = {
  inlayPanel: PanelResource;
  breadcrumbs?: ResourceBreadcrumb[];
  heading: string;
  subheading?: string | null;
  subNavigation?: ResourceSubNavigationItem[];
  table: TableResource;
  tabs?: ResourceTabsResource | null;
};

export default function UsersIndex({
  breadcrumbs = [],
  heading,
  subheading,
  subNavigation = [],
  table,
  tabs = null,
}: PageProps) {
  const { inlayPanel } = usePage<PageProps>().props;
  const theme = {
    contract: "inlay.themes.v1" as const,
    name: inlayPanel.themeName ?? inlayPanel.id,
    tokens: inlayPanel.theme,
    darkTokens: inlayPanel.darkTheme ?? {},
  };

  return (
    <InlayPanelLayout>
      <Head title={heading} />
      <ResourcePage
        actions={
          <Link
            className="inline-flex min-h-(--inlay-button-height) items-center rounded-(--inlay-radius) bg-(--inlay-accent) px-4 text-sm font-semibold text-(--inlay-accent-foreground)"
            href="/{{ panel }}/users/create"
          >
            Create user
          </Link>
        }
        breadcrumbs={breadcrumbs}
        heading={heading}
        subNavigation={subNavigation}
        subheading={subheading ?? "Create and maintain panel accounts."}
        tabs={tabs}
      >
        <section className="rounded-(--inlay-radius) border border-(--inlay-border) bg-(--inlay-surface) p-4 sm:p-6">
          <Table resource={table} theme={theme} />
        </section>
      </ResourcePage>
    </InlayPanelLayout>
  );
}
