// packages/form/vue/src/ActionForm.vue
<script setup lang="ts">
import type { VueActionRuntime } from '@inlayphp/actions-vue'
import { computed } from 'vue'
import Form from './Form.vue'
import type { FormErrors, FormResource } from './types'

const props = defineProps<{ controller: VueActionRuntime }>()
const form = computed(() => props.controller.state.value.form as FormResource | null)
const errors = computed<FormErrors>(() => Object.fromEntries(
  Object.entries(props.controller.state.value.validationErrors)
    .filter(([, messages]) => messages.length > 0)
    .map(([path, messages]) => [path, messages[0]!]),
))
function change(data: Record<string, unknown>) {
  props.controller.setData(data)
}
</script>

<template>
  <Form
    v-if="form"
    :errors="errors"
    manual
    :processing="controller.state.value.phase === 'executing'"
    :resource="form"
    :show-submit="false"
    @change="change"
    @submit="controller.confirm"
  />
</template>

// packages/form/react/src/ActionForm.tsx
import type { ReactActionRuntime } from '@inlayphp/actions-react'
import { Form } from './Form'
import type { FormProps } from './Form'
import type { FormErrors, FormResource } from './types'

export type ActionFormProps = Omit<FormProps, 'errors' | 'onSubmit' | 'processing' | 'resource' | 'showSubmit'> & {
  runtime: ReactActionRuntime
}

export function ActionForm({ runtime, onChange, ...props }: ActionFormProps) {
  const resource = runtime.state.form as FormResource | null
  if (!resource) return null
  const errors = Object.fromEntries(
    Object.entries(runtime.state.validationErrors)
      .filter(([, messages]) => messages.length > 0)
      .map(([path, messages]) => [path, messages[0]!]),
  )

  return <Form
    {...props}
    errors={errors satisfies FormErrors}
    onChange={(data) => {
      runtime.setData(data)
      onChange?.(data)
    }}
    onSubmit={() => void runtime.confirm()}
    processing={runtime.state.phase === 'executing'}
    resource={resource}
    showSubmit={false}
  />
}
