// playground/laravel-react/resources/js/vue/pages/users/form.vue
<script setup lang="ts">
import { Head, Link, router, usePage } from '@inertiajs/vue3';
import { Form } from '@inlayphp/forms-vue';
import type { FormErrors, FormResource } from '@inlayphp/forms-vue';
import { Panel } from '@inlayphp/panels-vue';
import type { PanelDirectoryEntry, PanelResource } from '@inlayphp/panels-vue';
import { RelationManagers } from '@inlayphp/resources-vue';
import type {
    RelationManagerResource,
    ResourceBreadcrumb,
    ResourceSubNavigationItem,
} from '@inlayphp/resources-vue';
import { ResourcePage } from '@inlayphp/resources-vue';
import AdminPanelHeader from '@/vue/components/admin-panel-header.vue';

type PageProps = {
    inlayPanel: PanelResource;
    inlayPanels: PanelDirectoryEntry[];
    resource: Record<string, unknown>;
    form: FormResource;
    record?: { id: number | string; name?: string };
    relations?: RelationManagerResource[];
    heading: string;
    subheading?: string | null;
    breadcrumbs?: ResourceBreadcrumb[];
    subNavigation?: ResourceSubNavigationItem[];
    errors?: FormErrors;
};

const page = usePage<PageProps>();
defineProps<PageProps>();
</script>

<template>
    <Head :title="heading" />
    <Panel
        :condition-values="{ resource, record }"
        :resource="inlayPanel"
        :on-navigate="(href) => router.visit(href)"
    >
        <template #header-end>
            <AdminPanelHeader
                :current-panel-id="inlayPanel.id"
                :panels="inlayPanels"
            />
        </template>

        <ResourcePage
            :breadcrumbs="breadcrumbs ?? []"
            :heading="heading"
            :subheading="subheading"
            :sub-navigation="subNavigation ?? []"
        >
            <template #actions>
                <Link
                    class="inline-flex min-h-10 items-center rounded-(--inlay-radius) border border-(--inlay-border) bg-(--inlay-surface) px-4 py-2 text-sm font-semibold text-(--inlay-text) transition-colors hover:bg-(--inlay-hover) focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-(--inlay-accent)"
                    href="/vue/resources/users"
                >
                    Back to users
                </Link>
            </template>

            <section
                class="min-w-0 rounded-(--inlay-radius) border border-(--inlay-border) bg-(--inlay-surface) p-5 shadow-sm"
                data-slot="vue-resource-form"
            >
                <Form :errors="page.props.errors ?? {}" :resource="form" />
            </section>

            <section
                v-if="record && relations?.length"
                class="mt-8 min-w-0 rounded-(--inlay-radius) border border-(--inlay-border) bg-(--inlay-surface) p-5 shadow-sm"
                data-slot="vue-resource-relations"
            >
                <RelationManagers
                    :resources="relations"
                    @changed="router.reload({ only: ['relations'] })"
                />
            </section>
        </ResourcePage>
    </Panel>
</template>

// playground/laravel-react/resources/js/pages/users/notes/form.tsx
import { Head, Link, usePage } from '@inertiajs/react';
import { Form } from '@inlayphp/forms-react';
import type { FormErrors, FormResource } from '@inlayphp/forms-react';
import AdminLayout from '@/layouts/admin-layout';

type PageProps = {
    form: FormResource;
    parentRecord: { id: number; name: string };
    record?: { id: number; title: string };
    errors: FormErrors;
};

export default function UserNoteFormPage({
    form,
    parentRecord,
    record,
}: PageProps) {
    const { errors } = usePage<PageProps>().props;

    return (
        <AdminLayout>
            <Head title={record ? `Edit ${record.title}` : 'Create note'} />
            <div className="mx-auto max-w-3xl rounded-2xl bg-white p-6 text-zinc-950 shadow-sm ring-1 ring-zinc-950/5 sm:p-8 dark:bg-zinc-900 dark:text-white dark:ring-white/10">
                <Link
                    className="text-sm font-medium text-zinc-500 transition-colors hover:text-zinc-950 dark:text-zinc-400 dark:hover:text-white"
                    href={`/admin/users/${parentRecord.id}/notes`}
                >
                    ← {parentRecord.name} notes
                </Link>
                <h1 className="mt-5 text-3xl font-semibold tracking-tight">
                    {record ? `Edit ${record.title}` : 'Create note'}
                </h1>
                <div className="mt-8">
                    <Form
                        errors={errors}
                        resource={form}
                        theme={{ accent: '#2563eb', radius: '0.625rem' }}
                    />
                </div>
            </div>
        </AdminLayout>
    );
}
